on:
  push:
    branches:
      - 'dev/**'
  workflow_dispatch:

name: "Publish development snapshot"

jobs:
  build:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: 'Build with Gradle'
        run: ./gradlew build
  publish-gh:
    name: 'Publish to GitHub Packages'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Set up JDK 8'
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: 'Publish with Gradle'
        run: ./gradlew publishAllPublicationsToRemoteRepository
        env:
          ORG_GRADLE_PROJECT_remoteURL: 'https://maven.pkg.github.com/sciwhiz12/Crucible'
          ORG_GRADLE_PROJECT_remoteUsername: ${{ env.GITHUB_ACTOR }}
          ORG_GRADLE_PROJECT_remotePassword: ${{ secrets.GITHUB_TOKEN }}